In [79]:
import numpy as np

In [80]:
# Создать вектор (одномерный массив) размера 10, заполненный нулями   
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
# Создать вектор размера 10, заполненный единицами 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
# Создать вектор размера 10, заполненный числом 2.5  
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [83]:
# Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1    
datal = np.zeros(10)
datal[4] = 1
datal

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [84]:
# Создать вектор со значениями от 10 до 49   
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [85]:
# Развернуть вектор (первый становится последним)   
vector = np.array([10, 50, 23, 16, 34, 45, 45])
revers = vector[::-1]
print(revers)

[45 45 34 16 23 50 10]


In [86]:
# Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8   
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
# Найти индексы ненулевых элементов в `[1,2,0,0,4,0]`   
arr = np.array([1,2,0,0,4,0])
np.where(arr == 0)[0]

array([2, 3, 5])

In [88]:
# Создать 3x3 единичную матрицу  
np.ones([3, 3], int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [89]:
# Создать массив 3x3x3 со случайными значениями 
np.random.random((3, 3, 3))

array([[[0.73226626, 0.54514079, 0.05426559],
        [0.29304597, 0.22277679, 0.25873232],
        [0.5777588 , 0.9279943 , 0.74532022]],

       [[0.03396199, 0.1376183 , 0.85288283],
        [0.62877451, 0.72453531, 0.8837524 ],
        [0.1097959 , 0.13802204, 0.34157147]],

       [[0.11905643, 0.9200667 , 0.41496073],
        [0.80773181, 0.44485577, 0.66283474],
        [0.00199813, 0.7551821 , 0.45186623]]])

In [90]:
# Создать массив 10x10 со случайными значениями, найти минимум и максимум   
arr = np.random.random((10, 10))
arr1 = arr.max()
arr2 = arr.min()
print(arr)
print(arr1)
print(arr2)

[[0.13614611 0.97040088 0.65034945 0.33863372 0.83435208 0.97904877
  0.84547367 0.69002219 0.10814318 0.70310058]
 [0.35930081 0.18459221 0.76225341 0.47155107 0.67014761 0.09979904
  0.72612658 0.40898546 0.99919703 0.60514606]
 [0.19716253 0.65723091 0.9363008  0.75450703 0.42958588 0.08759986
  0.64602369 0.21377478 0.18897852 0.33637503]
 [0.22266549 0.69561657 0.04242041 0.60309388 0.72311473 0.51780481
  0.61160071 0.88987228 0.38840399 0.3414583 ]
 [0.99013601 0.46085889 0.20540076 0.99633366 0.35804051 0.67943756
  0.08792475 0.8036343  0.48128345 0.10353997]
 [0.43898359 0.74056744 0.19047503 0.56335587 0.40962695 0.11406966
  0.01782278 0.15395506 0.93633095 0.65154314]
 [0.09203018 0.56308902 0.78282354 0.95218827 0.17503822 0.17279165
  0.85519747 0.84950407 0.96552784 0.65136417]
 [0.82851397 0.47111882 0.16889664 0.14126079 0.48715891 0.65470765
  0.70533406 0.48284629 0.49458103 0.99777751]
 [0.95340436 0.24860123 0.4991416  0.81846934 0.82282272 0.3779878
  0.06311791 

In [91]:
# Создать случайный вектор размера 30 и найти среднее значение всех элементов  
arr= np.random.random(30)
np.mean(arr)

np.float64(0.5256319169939868)

In [92]:
# Создать матрицу с 0 внутри, и 1 на границах
matrix = np.ones((10, 10))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [93]:
# Создать 5x5 матрицу с 1,2,3,4 под диагональю   
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [94]:
# Создать 8x8 матрицу и заполнить её в шахматном порядке    
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [95]:
# Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента? 
shape = (6, 7, 8)
index_100 = np.unravel_index(99, shape)
print(index_100)

(np.int64(1), np.int64(5), np.int64(3))
